#!/bin/bash


if [ $# -ne 2 ]; then
    echo "Error: Debes indicar 2 parámetros (origen y destino)."
    exit 1
fi

origen=$1
destino=$2


if [ ! -f "$origen" ]; then
    echo "Error: El archivo $origen no existe o no es un archivo ordinario."
    exit 1
fi


if [ -e "$destino" ]; then
    echo "Error: Ya existe un archivo o directorio llamado $destino."
    exit 1
fi


cp "$origen" "$destino"
echo "Archivo copiado correctamente de $origen a $destino"
