#!/bin/bash

echo "1) Sumar"
echo "2) Restar"
echo "3) Multiplicar"
echo "4) Dividir"

read -p "Elige una opción: " opcion

case $opcion in
    1) echo "¿Qué números quieres sumar?"
       read -p "Número 1: " num1
       read -p "Número 2: " num2
       echo "La suma de los números es igual a: $((num1 + num2))"
       ;;
    2) echo "¿Qué números quieres restar?"
       read -p "Número 1: " num1
       read -p "Número 2: " num2
       echo "La resta de los números es igual a: $((num1 - num2))"
       ;;
    3) echo "¿Qué números quieres multiplicar?"
       read -p "Número 1: " num1
       read -p "Número 2: " num2
       echo "La multiplicación de los números es igual a: $((num1 * num2))"
       ;;
    4) echo "¿Qué números quieres dividir?"
       read -p "Número 1: " num1
       read -p "Número 2: " num2
       if [ "$num2" -ne 0 ]; then
           echo "La división de los números es igual a: $((num1 / num2))"
       else
           echo "Error: No se puede dividir entre 0."
       fi
       ;;
    *) echo "Opción no válida"
       ;;
esac
