#!/bin/bash
ip addr show | egrep "inet "
ip route | grep "src"

for i in {1..10}
do
  ip="192.168.1.$i"
  ping -c1 -W1 $ip >/dev/null 2>&1
  if [ $? -eq 0 ]; then
    echo "$ip ocupada"
  else
    echo "$ip libre"
  fi
done
