#!/bin/bash
suma=0
for i in {1..1000}
do
  suma=$((suma+i))
done
echo $suma

suma=0
i=1
while [ $i -le 1000 ]
do
  suma=$((suma+i))
  i=$((i+1))
done
echo $suma

suma=0
i=1
until [ $i -gt 1000 ]
do
  suma=$((suma+i))
  i=$((i+1))
done
echo $suma
