#!/bin/bash
dir=$1
if [ -d "$dir" ]; then
    fecha=$(date +%F)
    tar -czf "${fecha}-$(basename $dir).tar.gz" "$dir"
    echo "Archivo comprimido creado: ${fecha}-$(basename $dir).tar.gz"
else
    echo "Error: el parámetro no es un directorio válido."
fi

